### ISSUE TITLE
Open Source Scos System Test

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city_test#19]
"As a developer implementing the Smart Cities data platform, I want an easy way to test against a data generating service.

Acceptance Criteria:
* The App is open sourced
  * Readme and documented
  * Licensed properly  

Technical Notes:
* Will need the TDG Library to be open sourced first or in parallel.

06-24-19: Migrated from SMRT-1387"

**Comment by rob-h-m** [comment]
rejected 08/14/19 by Carrie and Johnson
